# schema.act is generated by rfcgen.act by reading the YANG RFC 7950, which is
# stored in the rfc module.

all: out/bin/test_daclass

out/bin/test_daclass: src/y_cfs.act
	acton src/test_daclass.act

src/y_cfs.act: out/bin/gen_daclass
	out/bin/gen_daclass --rts-no-bt

out/bin/gen_daclass: src/gen_daclass.act src/yang/parser.act src/yang/schema.act
	acton src/gen_daclass.act

src/yang/schema.act: schema-header.act out/bin/rfcgen schema-footer.act
	(tail -n +4 schema-header.act && out/bin/rfcgen && cat schema-footer.act) > src/yang/schema.act

out/bin/rfcgen: src/rfcgen.act
	acton src/rfcgen.act

.PHONY: clean
clean:
	rm -rf out

