# schema.act is generated by rfcgen.act by reading the YANG RFC 7950, which is
# stored in the rfc module.

src/yang/schema.act: schema-manual.act out/bin/rfcgen
	(tail -n +4 schema-manual.act; out/bin/rfcgen) > src/yang/schema.act

out/bin/rfcgen:
	acton src/rfcgen.act
