# schema.act is generated by rfcgen.act by reading the YANG RFC 7950, which is
# stored in the rfc module.

all: out/bin/respnet

.PHONY: out/bin/respnet
out/bin/respnet: src/respnet.act src/respnet/layer.act
	acton src/respnet.act

src/respnet/layer.act: out/bin/respnet_gen
	out/bin/respnet_gen --rts-no-bt

out/bin/respnet_gen: src/respnet_gen.act src/yang/parser.act src/yang/schema.act
	acton src/respnet_gen.act

src/yang/schema.act: schema-header.act out/bin/rfcgen schema-footer.act
	(tail -n +4 schema-header.act && out/bin/rfcgen && cat schema-footer.act) > src/yang/schema.act

out/bin/rfcgen: src/rfcgen.act
	acton src/rfcgen.act

.PHONY: clean
clean:
	rm -rf out

